project:
  type: website

website:
  title: "Evil-detector"
  navbar:
    left:
      - href: index.ipynb
        text: Introduction
      - href: references.ipynb
        text: References
  favicon: images/favicon.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



