project:
  type: website

website:
  title: "Project"
  navbar:
    left:
      - href: index.ipynb
        text: Introduction
      - href: references.ipynb
        text: References

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



